export const phrases = [
  "fast paced",
  "future proof",
  "empowered",
  "enterprise ready",
  "scalable",
  "drive better",
  "tackle",
  "smart",
  "high performance",
  "blazingly fast",
  "next generation",
  "innovative",
  "cutting edge",
  "disruptive",
  "game changing",
  "paradigm shifting",
  "synergistic",
  "best in class",
  "world class",
  "state of the art",
  "top tier",
  "industry leading",
  "bleeding edge",
  "revolutionary",
  "groundbreaking",
  "transformative",
  "agile",
  "lean",
  "robust",
  "seamless",
  "frictionless",
  "streamlined",
  "optimized",
  "enhanced",
  "advanced",
  "sophisticated",
  "intuitive",
  "user friendly",
  "turnkey",
  "out of the box",
  "plug and play",
  "end to end",
  "full stack",
  "holistic",
  "comprehensive",
  "integrated",
  "unified",
  "cohesive",
  "synchronized",
  "aligned",
  "leveraged",
  "maximized",
  "amplified",
  "boosted",
  "accelerated",
  "turbo charged",
  "supercharged",
  "hyper growth",
  "exponential",
  "skyrocketing",
  "rocketing",
  "soaring",
  "quantum leap",
  "game changer",
  "differentiator",
  "unique value proposition",
  "competitive advantage",
  "top notch",
  "mission critical",
  "pivotal",
  "crucial",
  "essential",
  "indispensable",
  "vital",
  "core",
  "fundamental",
  "strategic",
  "tactical",
  "operational",
  "actionable",
  "results driven",
  "outcome oriented",
  "goal oriented",
  "solution focused",
  "customer centric",
  "client focused",
  "user centric",
  "human centered",
  "data driven",
  "insights driven",
  "analytics powered",
  "ai enabled",
  "ai powered",
  "machine learning powered",
  "cloud native",
  "cloud based",
  "cloud first",
  "mobile first",
  "digital first",
  "omnichannel",
  "multichannel",
  "cross functional",
  "interdisciplinary",
  "multidisciplinary",
  "transdisciplinary",
  "eco system",
  "network effect",
  "viral",
  "sticky",
  "engagement",
  "immersive",
  "experiential",
  "gamified",
  "personalized",
  "customized",
  "tailored",
  "bespoke",
  "on demand",
  "real time",
  "instantaneous",
  "lightning fast",
  "ultra fast",
  "hyper fast",
  "24/7",
  "always on",
  "always available",
  "uninterrupted",
  "continuous",
  "persistent",
  "perpetual",
  "evergreen",
  "sustainable",
  "green",
  "eco friendly",
  "environmentally conscious",
  "socially responsible",
  "ethical",
  "transparent",
  "authentic",
  "genuine",
  "trustworthy",
  "reliable",
  "dependable",
  "bulletproof",
  "foolproof",
  "fail safe",
  "resilient",
  "robust",
  "rugged",
  "industrial strength",
  "military grade",
  "bank grade",
  "enterprise grade",
  "carrier grade",
  "production ready",
  "battle tested",
  "proven",
  "tried and true",
  "time tested",
  "award winning",
  "acclaimed",
  "celebrated",
  "renowned",
  "prestigious",
  "elite",
  "premium",
  "luxury",
  "high end",
  "top of the line",
  "deluxe",
  "ultimate",
  "unparalleled",
  "unmatched",
  "unrivaled",
  "unbeatable",
  "second to none",
  "best of breed",
  "cream of the crop",
  "gold standard",
  "benchmark",
  "yardstick",
  "touchstone",
  "north star",
  "polestar",
  "guiding light",
  "beacon",
  "catalyst",
  "enabler",
  "facilitator",
  "accelerator",
  "incubator",
  "force multiplier",
  "secret weapon",
  "silver bullet",
  "magic bullet",
  "panacea",
  "cure all",
  "one stop shop",
  "all in one",
  "swiss army knife",
  "jack of all trades",
  "master of all",
  "polymath",
  "renaissance",
  "visionary",
  "forward thinking",
  "forward looking",
  "future oriented",
  "ahead of the curve",
  "ahead of the pack",
  "trailblazing",
  "pioneering",
  "pathfinding",
  "spearheading",
  "leading edge",
  "frontrunner",
  "pacesetter",
  "trendsetter",
  "thought leader",
  "influencer",
  "change agent",
  "disruptor",
  "innovator",
  "entrepreneur",
  "intrapreneur",
  "go getter",
  "self starter",
  "high flyer",
  "rainmaker",
  "dynamo",
  "powerhouse",
  "juggernaut",
  "titan",
  "behemoth",
  "colossus",
  "goliath",
  "leviathan",
  "mammoth",
  "gargantuan",
  "colossal",
  "titanic",
  "herculean",
  "epic",
  "monumental",
  "landmark",
  "milestone",
  "watershed",
  "inflection point",
  "tipping point",
  "turning point",
  "crossroads",
  "nexus",
  "epicenter",
  "focal point",
  "convergence",
  "confluence",
  "synergy",
  "symbiosis",
  "win win",
  "value add",
  "value added",
  "value proposition",
  "elevator pitch",
  "low hanging fruit",
  "quick win",
  "quick fix",
  "magic wand",
  "silver lining",
  "game plan",
  "playbook",
  "roadmap",
  "blueprint",
  "landscape",
  "terrain",
  "arena",
  "playing field",
  "incubator",
  "accelerator",
  "launchpad",
  "springboard",
  "stepping stone",
  "building block",
  "cornerstone",
  "keystone",
  "linchpin",
  "lynchpin",
  "fulcrum",
  "pivot",
  "axis",
  "nexus",
  "nucleus",
  "core",
  "heart",
  "soul",
  "lifeblood",
  "backbone",
  "bedrock",
  "grassroots",
  "ground up",
  "top down",
  "bottom up",
  "inside out",
  "outside in",
  "360 degree",
  "full circle",
  "end to end",
  "soup to nuts",
  "cradle to grave",
  "womb to tomb",
  "alpha to omega",
  "a to z",
  "turnkey",
  "one size fits all",
  "cookie cutter",
  "templated",
  "prefab",
  "out of the box",
  "ready made",
  "off the shelf",
  "plug and play",
  "mix and match",
  "modular",
  "customizable",
  "configurable",
  "flexible",
  "adaptable",
  "versatile",
  "multi purpose",
  "multi use",
  "multi functional",
  "Swiss Army knife",
  "jack of all trades",
  "all singing all dancing",
  "bells and whistles",
  "feature rich",
  "fully featured",
  "fully loaded",
  "maxed out",
  "souped up",
  "pimped out",
  "tricked out",
  "decked out",
  "kitted out",
  "tooled up",
  "geared up",
  "revved up",
  "amped up",
  "pumped up",
  "ramped up",
  "leveled up",
  "next level",
  "level up",
  "elevated",
  "supercharged",
  "turbocharged",
  "nitro boosted",
  "rocket fueled",
  "jet propelled",
  "warp speed",
  "light speed",
  "hyper speed",
  "ludicrous speed",
  "breakneck speed",
  "blistering pace",
  "lightning pace",
  "whirlwind pace",
  "meteoric rise",
  "stratospheric growth",
  "astronomical growth",
  "exponential growth",
  "hockey stick growth",
  "J curve",
  "S curve",
  "bell curve",
  "long tail",
  "blue ocean",
  "green field",
  "white space",
  "blank slate",
  "clean slate",
  "tabula rasa",
  "carte blanche",
  "open ended",
  "open book",
  "crowdsourced",
  "peer to peer",
  "collaborative",
  "co creative",
  "participatory",
  "inclusive",
  "diverse",
  "equitable",
  "universal",
  "global",
  "worldwide",
  "planet wide",
  "earth spanning",
  "borderless",
  "boundaryless",
  "limitless",
  "infinite",
  "endless",
  "perpetual",
  "eternal",
  "timeless",
  "ageless",
  "evergreen",
  "perennial",
  "persistent",
  "resilient",
  "antifragile",
  "unbreakable",
  "indestructible",
  "bulletproof",
  "bombproof",
  "shockproof",
  "failsafe",
  "foolproof",
  "idiot proof",
  "child's play",
  "walk in the park",
  "piece of cake",
  "easy as pie",
  "smooth sailing",
  "plain sailing",
  "clear sailing",
  "smooth running",
  "well oiled",
  "clockwork",
  "like clockwork",
  "military precision",
  "surgical precision",
  "laser focused",
  "pinpoint accuracy",
  "bullseye",
  "on target",
  "spot on",
  "dead on",
  "right on",
  "on point",
  "on the money",
  "bang on",
  "first rate",
  "first class",
  "world class",
  "best in class",
  "best of breed",
  "cream of the crop",
  "creme de la creme",
  "upper crust",
  "top drawer",
  "top shelf",
  "high end",
  "upmarket",
  "upscale",
  "premium",
  "luxe",
  "deluxe",
  "elite",
  "exclusive",
  "select",
  "choice",
  "prime",
  "blue ribbon",
  "gold star",
  "five star",
  "stellar",
  "exemplary",
  "model",
  "quintessential",
  "archetypal",
  "prototypical",
  "picture perfect",
  "flawless",
  "impeccable",
  "immaculate",
  "pristine",
  "mint",
  "mint condition",
  "showroom condition",
  "factory fresh",
  "box fresh",
  "good as new",
  "like new",
  "born again",
  "reborn",
  "rejuvenated",
  "revitalized",
  "reinvigorated",
  "reinvented",
  "reimagined",
  "redefined",
  "redesigned",
  "re engineered",
  "refactored",
  "remastered",
  "remixed",
  "rebooted",
  "revamped",
  "overhauled",
  "turbo charged",
  "supercharged",
  "nitrous injected",
  "high octane",
  "high powered",
  "high performance",
  "high spec",
  "spec'd out",
  "fully spec'd",
  "fully equipped",
  "fully loaded",
  "loaded to the gills",
  "all singing all dancing",
  "bells and whistles",
  "whistles and bells",
  "all the trimmings",
  "everything but the kitchen sink",
  "kitchen sink included",
  "no stone unturned",
  "leave no stone unturned",
  "cover all bases",
  "all bases covered",
  "all angles covered",
  "360 degree coverage",
  "full spectrum",
  "full gamut",
  "full monty",
  "whole nine yards",
  "whole enchilada",
  "whole kit and caboodle",
  "whole shebang",
  "whole ball of wax",
  "lock stock and barrel",
  "hook line and sinker",
  "from soup to nuts",
  "from a to z",
  "from start to finish",
  "from conception to completion",
  "from ideation to execution",
  "from brainstorm to boardroom",
  "from whiteboard to dashboard",
  "from back of napkin to back of envelope",
  "from zero to hero",
  "from good to great",
  "from great to greater",
  "from better to best",
  "best of the best",
  "cream of the crop",
  "top of the heap",
  "king of the hill",
  "top dog",
  "big kahuna",
  "head honcho",
  "main event",
  "headline act",
  "star of the show",
  "showstopper",
  "crowd pleaser",
  "fan favorite",
  "chart topper",
  "blockbuster",
  "smash hit",
  "runaway success",
  "overnight sensation",
  "instant classic",
  "timeless classic",
  "modern classic",
  "new classic",
  "future classic",
  "cult classic",
  "sleeper hit",
  "dark horse",
  "underdog",
  "comeback kid",
  "phoenix from the ashes",
  "rags to riches",
  "zero to hero",
  "diamond in the rough",
  "hidden gem",
  "best kept secret",
  "well kept secret",
  "insider secret",
  "trade secret",
  "secret sauce",
  "special sauce",
  "magic formula",
  "winning formula",
  "success formula",
  "growth hack",
  "life hack",
  "pro tip",
  "power move",
  "power play",
  "checkmate",
  "mic drop",
  "slam dunk",
  "home run",
  "touchdown",
  "grand slam",
  "hole in one",
  "bullseye",
  "perfect 10",
  "full marks",
  "top marks",
  "high score",
  "high water mark",
  "gold standard",
  "platinum standard",
  "diamond standard",
  "benchmark",
  "yardstick",
  "measuring stick",
  "litmus test",
  "acid test",
  "stress test",
  "baptism by fire",
  "trial by fire",
  "sink or swim",
  "make or break",
  "do or die",
  "now or never",
  "moment of truth",
  "zero hour",
  "eleventh hour",
  "crunch time",
  "decision time",
  "tipping point",
  "turning point",
  "inflection point",
  "pivot point",
  "pain point",
  "pressure point",
  "pinch point",
  "choke point",
  "bottleneck",
  "roadblock",
  "stumbling block",
  "hurdle",
  "obstacle",
  "challenge",
  "opportunity",
  "low hanging fruit",
  "quick win",
  "easy win",
  "small win",
  "big win",
  "win win",
  "win win win",
  "triple win",
  "grand slam",
  "royal flush",
  "jackpot",
  "bonanza",
  "goldmine",
  "cash cow",
  "golden goose",
  "goose that lays golden eggs",
  "gift that keeps on giving",
  "perpetual motion machine",
  "money printing machine",
  "license to print money",
  "blank check",
  "carte blanche",
  "free rein",
  "green light",
  "all systems go",
  "full steam ahead",
  "pedal to the metal",
  "balls to the wall",
  "no holds barred",
  "gloves off",
  "bare knuckle",
  "down and dirty",
  "nitty gritty",
  "brass tacks",
  "nuts and bolts",
  "meat and potatoes",
  "bread and butter",
  "day in day out",
  "24/7/365",
  "round the clock",
  "non stop",
  "always on",
  "ever ready",
  "ever vigilant",
  "eagle eyed",
  "hawk eyed",
  "laser focused",
  "tunnel vision",
  "heads down",
  "nose to the grindstone",
  "shoulder to the wheel",
  "sleeves rolled up",
  "all hands on deck",
  "all aboard",
  "team effort",
  "group effort",
  "collective effort",
  "collaborative effort",
  "synergistic effort",
  "force multiplier",
  "strength in numbers",
  "power in numbers",
  "safety in numbers",
  "wisdom of crowds",
  "hive mind",
  "groupthink",
  "think tank",
  "brain trust",
  "mastermind group",
  "inner circle",
  "inner sanctum",
  "ivory tower",
  "echo chamber",
  "bubble",
  "silo",
  "vacuum",
  "black box",
  "magic box",
  "pandora's box",
  "can of worms",
  "rabbit hole",
  "rat race",
  "hamster wheel",
  "treadmill",
  "conveyor belt",
  "assembly line",
  "production line",
  "supply chain",
  "value chain",
  "food chain",
  "pecking order",
  "hierarchy",
  "pyramid",
  "top down",
  "bottom up",
  "grassroots",
  "ground up",
  "soup to nuts",
  "end to end",
  "full stack",
  "full cycle",
  "cradle to grave",
  "womb to tomb",
  "alpha to omega",
  "genesis to revelation",
  "big bang to heat death",
  "micro to macro",
  "atomic to cosmic",
  "quantum to galactic",
  "nano to giga",
  "micro to mega",
  "mini to maxi",
  "local to global",
  "personal to universal",
  "specific to general",
  "concrete to abstract",
  "tactical to strategic",
  "operational to visionary",
  "short term to long term",
  "quick fix to lasting solution",
  "band aid to cure",
  "symptom to cause",
  "problem to solution",
  "challenge to opportunity",
  "weakness to strength",
  "threat to advantage",
  "liability to asset",
  "cost to investment",
  "expense to revenue",
  "lead to gold",
  "zero to hero",
  "startup to unicorn",
  "small business to enterprise",
  "local to multinational",
  "domestic to international",
  "regional to global",
  "earth to space",
  "offline to online",
  "analog to digital",
  "legacy to cutting edge",
  "traditional to disruptive",
  "conventional to revolutionary",
  "evolutionary to revolutionary",
  "incremental to breakthrough",
  "linear to exponential",
  "arithmetic to geometric",
  "additive to multiplicative",
  "good to great",
  "great to exceptional",
  "exceptional to transcendent",
  "human to superhuman",
  "mortal to immortal",
  "finite to infinite",
  "temporal to eternal",
  "material to spiritual",
  "mundane to sublime",
  "ordinary to extraordinary",
  "mediocre to magnificent",
  "average to awesome",
  "run of the mill to one of a kind",
  "commodity to luxury",
  "mass market to bespoke",
  "off the rack to tailor made",
  "generic to branded",
  "white label to premium label",
  "no name to household name",
  "unknown to famous",
  "niche to mainstream",
  "cult following to mass appeal",
  "insider secret to common knowledge",
  "hidden gem to crown jewel",
  "underdog to top dog",
  "dark horse to front runner",
  "long shot to sure bet",
  "risky bet to safe bet",
  "speculative to proven",
  "experimental to established",
  "beta to release",
  "prototype to product",
  "concept to reality",
  "idea to implementation",
  "vision to execution",
  "dream to reality",
  "fantasy to fact",
  "fiction to non fiction",
  "make believe to matter of fact",
  "virtual to actual",
  "potential to kinetic",
  "dormant to active",
  "latent to manifest",
  "implicit to explicit",
  "tacit to articulated",
  "intuitive to analytical",
  "gut feeling to data driven",
  "qualitative to quantitative",
  "subjective to objective",
  "anecdotal to empirical",
  "theoretical to practical",
  "academic to applied",
  "pure to applied",
  "basic to advanced",
  "novice to expert",
  "amateur to professional",
  "generalist to",
];
